export enum College {
  COLAMRUD = "COLAMRUD",
  COLANIM = "COLANIM",
  COLBIOS = "COLBIOS",
  COLCOMP = "COLCOMP",
  COLENDS = "COLENDS",
  COLENG = "COLENG",
  COLERM = "COLERM",
  COLFHEC = "COLFHEC",
  COLPHYS = "COLPHYS",
  COLPLANT = "COLPLANT",
  COLVET = "COLVET",
  FUMMSA = "FUMMSA"
}
